name: Git upstream update

on:
  schedule:
  - cron: 0 2 * * *
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update master
      env: 
        GITHUB_TOKEN : ${{ secrets.PUSH_TOKEN }}
      run: |
        git remote set-url origin https://Kukkerem:"${GITHUB_TOKEN}"@github.com/Kukkerem/bank2ynab.git
        git remote add upstream https://github.com/bank2ynab/bank2ynab.git
        git remote update
        git checkout --track origin/master
        git config --global user.email "kukkerem@gmail.com"
        git config --global user.name "Kukkerem"
        git merge upstream/master
        git push | true
